name: imlonghao/serverinfo:server

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/server.yml
      - server/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: imlonghao/serverinfo:server
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: server
